BTL_ClothesStore/Controllers/CartController.cs
using BTL_ClothesStore.Extension;
using BTL_ClothesStore.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BTL_ClothesStore.Controllers
{
    public class CartController : Controller
    {


        ClothesStoreContext DbContext = new ClothesStoreContext();
        public CartController(ClothesStoreContext _context)
        {
            DbContext = _context;
        }
        public List<CartModel> carts
        {
            get
            {
                var data = HttpContext.Session.Get<List<CartModel>>("GioHang");
                if(data == null) {
                    data = new List<CartModel>();
                }
                return data;
            }
     
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View(carts);
        }
        public IActionResult AddToCart(int id, int quantity)
        {
            var myCart = carts;
            var item = myCart.SingleOrDefault(p => p.product.ProductId == id);
            if(item == null)
            {
                var _product = DbContext.Products.SingleOrDefault(p => p.ProductId == id);
                item = new CartModel
                {
                    product = _product,
                    _quantity = quantity,
                    _price = (double)(quantity * _product.ProductPrice)
                };
                myCart.Add(item);
            }
            else
            {
                var _product = DbContext.Products.SingleOrDefault(p => p.ProductId == id);
                item._quantity += quantity;
                item._price += quantity*_product.ProductPrice;
            }
      
            HttpContext.Session.Set("GioHang", myCart);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id) 
        {
            var myCart = carts;
            var item = myCart.SingleOrDefault(r => r.product.ProductId == id);
            myCart.Remove(item);
            HttpContext.Session.Set("GioHang", myCart);
            return RedirectToAction(nameof(Index));
        }
    }
}

BTL_ClothesStore/Controllers/ContactController.cs
using BTL_ClothesStore.Extension;
using BTL_ClothesStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BTL_ClothesStore.Controllers
{
    public class ContactController : Controller
    {
        ClothesStoreContext DbContext = new ClothesStoreContext();
        public ContactController(ClothesStoreContext _context)
        {
            DbContext = _context;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SendFeedBack(string content)
        {
            if (HttpContext.Session.Get("UserAccount") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                if(content != null)
                {
                    FeedBack feedBack = new FeedBack();
                    var useracc = HttpContext.Session.GetString("UserAccount");
                    var acc = DbContext.Accounts.SingleOrDefault(p => p.UserAccount == useracc);
                    feedBack.FeedBackContent = content;
                    feedBack.AccountId = acc.AccountId;
                    DbContext.FeedBacks.Add(feedBack);
                    DbContext.SaveChanges();
                    return View();
                }
                return RedirectToAction(nameof(Index));  
            }
            
        }
    }
}

BTL_ClothesStore/Controllers/ProductController.cs
using BTL_ClothesStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace ClothesStore.Controllers
{
    public class ProductController : Controller
    {
        ClothesStoreContext DbContext = new ClothesStoreContext();
        public ProductController(ClothesStoreContext _context)
        {
            DbContext = _context;
        }
        [HttpGet]
        public IActionResult Index(int ?page)
        {
            int pageSize = 8;
            ViewBag.Brand = DbContext.Brands;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var products = DbContext.Products.AsNoTracking().OrderBy(x => x.ProductName);
            PagedList<Product> list = new PagedList<Product>(products, pageNumber, pageSize);
            return View(list);

        }
        [HttpGet]
        public IActionResult ProductByCategory(int id, int? page)
        {
            int pageSize = 8;
            ViewBag.Brand = DbContext.Brands;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var products = DbContext.Products.Where(x => x.CategoryId == id).AsNoTracking().OrderBy(x => x.ProductName);
            PagedList<Product> list = new PagedList<Product>(products, pageNumber, pageSize);
            return View(list);
        }
        [HttpGet]
        public IActionResult ProductByBrand(int id, int? page)
        {
            int pageSize = 8;
            ViewBag.Brand = DbContext.Brands;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var products = DbContext.Products.Where(x => x.BrandId == id).AsNoTracking().OrderBy(x => x.ProductName);
            PagedList<Product> list = new PagedList<Product>(products, pageNumber, pageSize);
            return View(list);
        }
        [HttpGet]
        public IActionResult ProductDetail(int id)
        {
            var product = DbContext.Products.Find(id);
            ViewBag.Brand = DbContext.Brands;
            return View(product);
        }
    }
}

BTL_ClothesStore/ViewComponents/BrandViewComponent.cs
using BTL_ClothesStore.Models;
using BTL_ClothesStore.Repository;
using Microsoft.AspNetCore.Mvc;

namespace BTL_ClothesStore.ViewComponents
{
    public class BrandViewComponent : ViewComponent
    {
        private readonly IBrandRepository _brand;
        public BrandViewComponent(IBrandRepository brandRepository)
        {
            _brand = brandRepository;
        }
        public IViewComponentResult Invoke()
        {
            var brand = _brand.GetAllBrands().OrderBy(x => x.BrandName);
            return View(brand);
        }
    }
}

BTL_ClothesStore/Views/Shared/ProductLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link rel="stylesheet" href="~/css/Style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <title>Shop_quan_ao</title>
</head>
<body>
    <!-- Heading start-->
    <section id="header">
        <a href="#"><img src="~/Image/logo/logo.jpg" class="logo"></a>
        <div>
            <ul id="navbar">
                <li><a asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                <li><a asp-controller="Product" asp-action="Index">Sản Phẩm</a></li>
                <li><a asp-controller="Home" asp-action="About">Về Chúng Tôi<i></i></a></li>
                <li><a asp-controller="Contact" asp-action="Index">Liên hệ</a></li>
                <li><a asp-controller="Cart" asp-action="Index">Giỏ Hàng</a></li>
                <li>
                    <a href="#" id="dropdown-toggle">Tài Khoản</a>
                    <ul class="dropdown">
                        <li id="dropdown-child"><a asp-controller="Account" asp-action="Login">Đăng Nhập</a></li>
                        <li><a asp-controller="Account" asp-action="Register">Đăng Kí</a></li>
                        <li><a asp-controller="Account" asp-action="Logout">Đăng Xuất</a></li>
                    </ul>
                </li>
                <a href="#" id="close"><i class="fas fa-times"></i></a>
            </ul>
        </div>
    </section>

    <section id="page-header">
        <h2>#Stayhome</h2>
        <p>Tiết kiệm nhiều hơn với phiếu giảm giá lên đến 70%</p>
    </section>

    <!-- Phan loai begin-->
    <section class="hero hero-normal">
        <div class="container1">
            <div class="row">
                <div>
                    <div class="hero__categories">
                        <div class="hero__categories__all" id="all-departments">
                            <i class="fa fa-bars"></i>
                            <span>All departments</span>
                        </div>
                        <ul id="department-list" style="display: none">
                            @await Component.InvokeAsync("Category")
                            <hr>
                            @await Component.InvokeAsync("Brand")
                        </ul>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="hero__search">
                        <div class="hero__search__form">
                            <form action="#">
                                <div class="hero__search__categories">
                                    All Categories
                                    <span class="arrow_carrot-down"></span>
                                </div>
                                <input type="text" placeholder="What do yo u need?">
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                        <div class="hero__search__phone">
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="hero__search__phone__text">
                                <h5>+65 11.188.888</h5>
                                <span>support 24/7 time</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Phan loai End -->

    <div>
        @RenderBody()
    </div>
    <!-- Foooter start-->
    <hr />
    <footer class="section-p1">
        <div class="col">
            <img class="logo" src="~/Image/logo/logo.jpg" alt="">
            <h4>Liên hệ</h4>
            <p><strong>Address:</strong> 255 Cầu Giấy,Quận Cầu Giấy,Hà Nội</p>
            <p><strong>Phone:</strong> 0978347567</p>
            <p><strong>Hours:</strong> 8:00AM - 22:00PM</p>

            <div class="follow">
                <h4>Theo dõi trang</h4>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-tiktok"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-youtube"></i>
                    <i class="fab fa-pinterest"></i>
                </div>
            </div>
        </div>
        <div class="col">
            <h4>Bao Gồm</h4>
            <a asp-controller="Home" asp-action="About">Về Chúng Tôi </a>
            <a href="#">Chính sách bảo mật</a>
            <a href="#">Các Điều Khoản</a>
            <a asp-controller="Contact" asp-action="Index">Liên Hệ </a>
        </div>
        <div class="col">
            <h4>Tài khoản của tôi</h4>
            <a asp-controller="Account" asp-action="Login">Đăng Nhập</a>
            <a asp-controller="Cart" asp-action="Index">Xem Giỏ Hàng</a>
            <a href="#">Sản Phẩm Yêu Thích</a>
            <a href="#">Giúp đỡ</a>
        </div>
        <div class="col install">
            <h4>Tải Ứng Dụng</h4>
            <p>Tải Từ AppStore hoặc GooglePlay</p>
            <div class="row">
                <img src="~/Image/ImageFooter/app.jpg" alt="">
                <img src="~/Image/ImageFooter/play.jpg" alt="">
            </div>
        </div>

        <div class="copyright">
            <p>© Copyrights 2023 by Cara</p>
        </div>
    </footer>
    <script src="~/js/ProductScript.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("scripts", required:false);
</body>
</html>

BTL_ClothesStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link rel="stylesheet" href="~/css/Style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <title>Shop_quan_ao</title>
</head>
<body>
    <!-- Heading start-->
    <section id="header">
        <a href="#"><img src="~/Image/logo/logo.jpg" class="logo"></a>
        <div>
            <ul id="navbar">
                <li><a asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                <li><a asp-controller="Product" asp-action="Index">Sản Phẩm</a></li>
                <li><a asp-controller="Home" asp-action="About">Về Chúng Tôi<i></i></a></li>
                <li><a asp-controller="Contact" asp-action="Index">Liên hệ</a></li>
                <li><a asp-controller="Cart" asp-action="Index">Giỏ Hàng</a></li>
                <li>
                    <a href="#" id="dropdown-toggle">Tài Khoản</a>
                    <ul class="dropdown">
                        <li id="dropdown-child"><a asp-controller="Account" asp-action="Login">Đăng Nhập</a></li>
                        <li><a asp-controller="Account" asp-action="Register">Đăng Kí</a></li>
                        <li><a asp-controller="Account" asp-action="Logout">Đăng Xuất</a></li>
                    </ul>
                </li>
                <a href="#" id="close"><i class="fas fa-times"></i></a>
            </ul>
            <div id="mobile">
                <i id="bar" class="fas  fa-outdent"></i>
            </div>
        </div>
    </section>
    <!-- Heading end-->
    <div>
        @RenderBody()
    </div>
    <!-- Foooter start-->
    <hr />
    <footer class="section-p1">
        <div class="col">
            <img class="logo" src="~/Image/logo/logo.jpg" alt="">
            <h4>Liên hệ</h4>
            <p><strong>Address:</strong> 255 Cầu Giấy,Quận Cầu Giấy,Hà Nội</p>
            <p><strong>Phone:</strong> 0978347567</p>
            <p><strong>Hours:</strong> 8:00AM - 22:00PM</p>

            <div class="follow">
                <h4>Theo dõi trang</h4>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-tiktok"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-youtube"></i>
                    <i class="fab fa-pinterest"></i>
                </div>
            </div>
        </div>
        <div class="col">
            <h4>Bao Gồm</h4>
            <a asp-controller="Home" asp-action="About">Về Chúng Tôi </a>
            <a href="#">Chính sách bảo mật</a>
            <a href="#">Các Điều Khoản</a>
            <a asp-controller="Contact" asp-action="Index">Liên Hệ </a>
        </div>
        <div class="col">
            <h4>Tài khoản của tôi</h4>
            <a asp-controller="Account" asp-action="Login">Đăng Nhập</a>
            <a asp-controller="Cart" asp-action="Index">Xem Giỏ Hàng</a>
            <a href="#">Sản Phẩm Yêu Thích</a>
            <a href="#">Giúp đỡ</a>
        </div>
        <div class="col install">
            <h4>Tải Ứng Dụng</h4>
            <p>Tải Từ AppStore hoặc GooglePlay</p>
            <div class="row">
                <img src="~/Image/ImageFooter/app.jpg" alt="">
                <img src="~/Image/ImageFooter/play.jpg" alt="">
            </div>
        </div>

        <div class="copyright">
            <p>© Copyrights 2023 by Cara</p>
        </div>
    </footer>
    <script src="~/js/ProductScript.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("scripts", required:false);
</body>
</html>